<?php
if (isset($_POST['settings'])) {
	//$initDir = $_POST['init_dir'];
	$base = $_POST['base'];
	if (empty($base)) {
		$base = '/';
	}
	$settings = $_POST['settings'];
	if (isset($_POST['delete'])) {
		$delete = $_POST['delete'];
	} else {
		$delete = 'false';
	}
	

	if ($htaccess = fopen('.htaccess', 'a')) {
		fwrite($htaccess, "# --URLS BEGIN--\n# The following lines between \"--URLS BEGIN--\" and \"--URLS END--\" are\n# automatically generated by the URLS framework. These lines should\n# not be edited as it may result in unwanted behavior of the site. Any\n# edits made may be overwritten automatically.\nOptions +FollowSymLinks\nRewriteEngine On\nRewriteBase ".$base."\nRewriteRule ^".preg_quote($settings)."$ - [L]\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule . ".$base.$settings." [L]\n# --URLS END--\n");
		fclose($htaccess);
	} else {
		die('Error creating ".htaccess" file.');
	}

	if (!is_dir('urls')) {
		$dir = 'urls';
	} else {
		$dir = 'urls_'.uniqid();
	}
	mkdir($dir);
	if ($urls = fopen('https://raw.githubusercontent.com/micahbaumann/URLS/main/scr/urls.php', 'r')) { 
		file_put_contents($dir.'/urls.php', $urls);
		fclose($urls);
	} else {
		die('Error creating "urls.php" file.');
	}

	if ($update = fopen('https://raw.githubusercontent.com/micahbaumann/URLS/main/scr/update.php', 'r')) { 
		file_put_contents($dir.'/update.php', $update);
		fclose($update);
	} else {
		die('Error creating "update.php" file.');
	}

	if ($license = fopen('https://raw.githubusercontent.com/micahbaumann/URLS/main/scr/update.php', 'r')) { 
		file_put_contents($dir.'/LICENSE', $license);
		fclose($license);
	} else {
		die('Error creating "LICENSE" file.');
	}

	$settingsFile = fopen($settings, 'w');
	fwrite($settingsFile, "<?php\n/*\nURLS framework url config file.\n\nAdd your paths here:\nex. path('blog/', 'blog-home.php');\n*/\ninclude '".$dir."/urls.php';\n\$BASE_URL = ".$base.";\n\n\nurls_404();\n\n?>\n");
	fclose($settingsFile);
	echo 'done';
	if ($delete == 'true') {
		unlink('urls_welcome.php');
	}
	exit();

}
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>URLS - Welcome!</title>
</head>
<body>
	<form method="post">
		<!--<label>Install Directory (leave blank for the current directory): <input type="text" name="init_dir" placeholder="ex. /your/path/"></label><br>-->
		<label>Base Directory: <input type="text" name="base" placeholder="ex. /your/path/"></label><br>
		<label>Settings File (if the file already exists, it will be overwritten): <input type="text" name="settings" placeholder="ex. settings.php"></label><br>
		<label><input type="checkbox" name="delete" value="true">Would you like to delete this file after installation? (recomended for production)</label><br>
		<button	type="submit">Install</button>
	</form>
</body>
</html>